# Generated by Django 5.1.4 on 2026-09-02 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('network_type', models.CharField(choices=[('any', 'Любой'), ('wired', 'Проводной'), ('wireless', 'Беспроводной'), ('vpn', 'VPN'), ('admin', 'Административный')], default='any', max_length=16)),
                ('group', models.CharField(default='any', max_length=140)),
                ('mfa_required', models.BooleanField(default=True)),
                ('effect', models.CharField(choices=[('allow', 'Разрешить'), ('deny', 'Запретить'), ('review', 'На проверку')], default='allow', max_length=16)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_matched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True)),
                ('component', models.CharField(choices=[('firewall', 'Межсетевой экран'), ('ips', 'Система обнаружения вторжений'), ('edr', 'Защита серверов и рабочих станций'), ('web_filter', 'Интернет-доступ и фильтрация'), ('access', 'Доступ и MFA'), ('siem', 'SIEM и мониторинг логов')], default='siem', max_length=32)),
                ('pattern', models.CharField(max_length=280)),
                ('threshold', models.PositiveIntegerField(default=3)),
                ('window_minutes', models.PositiveIntegerField(default=10)),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критичная')], default='high', max_length=16)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EDRPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True)),
                ('telemetry_level', models.CharField(default='standard', max_length=40)),
                ('block_usb', models.BooleanField(default=False)),
                ('block_script_interpreters', models.BooleanField(default=True)),
                ('quarantine_on_malware', models.BooleanField(default=True)),
                ('protected_paths', models.TextField(default='/etc\n/var/www\nC:\\Windows\\System32')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('action', models.CharField(choices=[('allow', 'Разрешить'), ('block', 'Блокировать'), ('reject', 'Отклонить'), ('log', 'Только логировать')], default='block', max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'Входящий'), ('outbound', 'Исходящий'), ('any', 'Любой')], default='any', max_length=16)),
                ('protocol', models.CharField(choices=[('any', 'Любой'), ('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP')], default='any', max_length=16)),
                ('source_cidr', models.CharField(default='any', max_length=64)),
                ('destination_cidr', models.CharField(default='any', max_length=64)),
                ('destination_port', models.CharField(default='any', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_matched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IPSRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('match_field', models.CharField(choices=[('payload', 'Payload'), ('url', 'URL'), ('message', 'Message')], default='payload', max_length=16)),
                ('pattern', models.CharField(max_length=280)),
                ('action', models.CharField(choices=[('alert', 'Создать алерт'), ('block', 'Блокировать')], default='alert', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критичная')], default='high', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_matched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('component', models.CharField(choices=[('firewall', 'Межсетевой экран'), ('ips', 'Система обнаружения вторжений'), ('edr', 'Защита серверов и рабочих станций'), ('web_filter', 'Интернет-доступ и фильтрация'), ('access', 'Доступ и MFA'), ('siem', 'SIEM и мониторинг логов')], default='siem', max_length=32)),
                ('parser', models.CharField(choices=[('json', 'JSON'), ('syslog', 'Syslog'), ('plain', 'Plain text')], default='json', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('firewall', 'Межсетевой экран'), ('ips', 'Система обнаружения вторжений'), ('edr', 'Защита серверов и рабочих станций'), ('web_filter', 'Интернет-доступ и фильтрация'), ('access', 'Доступ и MFA'), ('siem', 'SIEM и мониторинг логов')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('monitor', 'Мониторинг'), ('enforce', 'Применение'), ('disabled', 'Отключено')], default='monitor', max_length=16)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='WebFilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('match_type', models.CharField(choices=[('domain', 'Домен'), ('contains', 'Содержит'), ('regex', 'Regex')], default='domain', max_length=16)),
                ('pattern', models.CharField(max_length=260)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('allow', 'Разрешить'), ('block', 'Блокировать'), ('review', 'На проверку')], default='block', max_length=16)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_matched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='endpointasset',
            name='operating_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='endpointasset',
            name='owner',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='securitycomponent',
            name='category',
            field=models.CharField(choices=[('firewall', 'Межсетевой экран'), ('ips', 'Система обнаружения вторжений'), ('edr', 'Защита серверов и рабочих станций'), ('web_filter', 'Интернет-доступ и фильтрация'), ('access', 'Доступ и MFA'), ('siem', 'SIEM и мониторинг логов')], max_length=32),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='destination',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='source_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('firewall', 'Межсетевой экран'), ('ips', 'Система обнаружения вторжений'), ('edr', 'Защита серверов и рабочих станций'), ('web_filter', 'Интернет-доступ и фильтрация'), ('access', 'Доступ и MFA'), ('siem', 'SIEM и мониторинг логов')], default='siem', max_length=32)),
                ('raw_message', models.TextField()),
                ('parsed', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('destination', models.CharField(blank=True, max_length=180)),
                ('event_type', models.CharField(default='Log event', max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критичная')], default='low', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='api.securityevent')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.logsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
